default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_stages: [commit, push]
repos:
  - repo: local
    hooks:
      - id: format
        name: Format using Ruff
        entry: ruff format
        language: python
        types: [python]
        pass_filenames: false
      - id: commitizen
        name: Check commit message
        entry: cz check
        args: [--allow-abort, --commit-msg-file]
        stages: [commit-msg]
        language: python
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data
        entry: trufflehog git file://. --since-commit HEAD --only-verified
        language: system
        pass_filenames: false
