[tool.poetry]
    name        = "langmax"
    version     = "0.1.0"
    description = "Leveraging the capabilities of LLMs to improve day-to-day tasks."
    authors     = ["Alex <30626291+ipruning@users.noreply.github.com>"]
    readme      = "README.md"

[tool.poetry.dependencies]
    anthropic        = "^0.25.1"
    black            = { extras = ["jupyter"], version = "^23.7.0" }
    chainlit         = "^1.0.400"
    datasets         = "^2.18.0"
    einops           = "^0.7.0"
    flask            = "^3.0.2"
    gradio           = "^4.21.0"
    httpx            = { extras = ["socks"], version = "^0.27.0" }
    langchain        = "^0.1.12"
    lark-oapi        = "^1.2.4"
    litellm          = "^1.34.4"
    llama-cpp-python = { extras = ["server"], version = "^0.2.61" }
    llama-index      = "^0.10.28"
    lmql             = "^0.7.3"
    matplotlib       = "^3.8.4"
    mlx              = "^0.10.0"
    numpy            = "^1.26.4"
    openai           = "^1.17.1"
    pandas           = "^2.2.2"
    parea-ai         = "^0.2.98"
    portkey-ai       = "^1.2.3"
    python           = ">=3.10.0, <3.13.0"
    python-dotenv    = "^1.0.1"
    ragas            = "^0.1.7"
    replicate        = "^0.25.1"
    rich             = "^13.7.1"
    sentencepiece    = "^0.2.0"
    tenacity         = "^8.2.3"
    tiktoken         = "^0.6.0"
    tqdm             = "^4.66.2"
    transformers     = { extras = ["torch"], version = "^4.39.2" }

[build-system]
    build-backend = "poetry.core.masonry.api"
    requires      = ["poetry_core>=1.0.0"]
