[project]
    name = "langmax"
    version = "0.1.0"
    description = "Leveraging the capabilities of LLMs to improve day-to-day tasks."
    authors = [
        { name = "Alex", email = "30626291+ipruning@users.noreply.github.com" },
    ]
    readme = "README.md"
    requires-python = ">=3.12"
    dependencies = [
        "baml-py>=0.57.0",
        "google-generativeai>=0.8.2",
        "joblib>=1.4.2",
        "logfire>=0.55.0",
        "marimo>=0.8.22",
        "openai>=1.50.2",
        "pydantic>=2.9.2",

    ]

[tool.pyright]
    pythonVersion = "3.12"
    venv          = ".venv"
    venvPath      = "."

    typeCheckingMode     = "standard"
    reportMissingImports = false

[tool.uv]
    managed = true
    package = true

    dev-dependencies = [
        "commitizen>=3.29.1",
        "httpx[socks]>=0.27.2",
        "ruff~=0.6.8",
    ]

[tool.ruff]
    exclude = [
        ".bzr",
        ".direnv",
        ".eggs",
        ".git",
        ".git-rewrite",
        ".hg",
        ".ipynb_checkpoints",
        ".mypy_cache",
        ".nox",
        ".pants.d",
        ".pyenv",
        ".pytest_cache",
        ".pytype",
        ".ruff_cache",
        ".svn",
        ".tox",
        ".venv",
        ".vscode",
        "__pypackages__",
        "_build",
        "buck-out",
        "build",
        "dist",
        "node_modules",
        "site-packages",
        "venv",
    ]
    indent-width = 4
    line-length = 180
    target-version = "py312"

[tool.ruff.lint]
    select    = ["A", "E", "F", "I", "N", "T100"]
    ignore    = ["E501"]
    fixable   = ["ALL"]
    unfixable = []

    dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
    quote-style                = "double"
    indent-style               = "space"
    skip-magic-trailing-comma  = false
    line-ending                = "auto"
    docstring-code-format      = true
    docstring-code-line-length = "dynamic"
