[tool.poetry]
    name        = "langmax"
    version     = "0.1.0"
    description = ""
    authors     = ["Alex <30626291+ipruning@users.noreply.github.com>"]
    readme      = "README.md"

[tool.poetry.dependencies]
    python        = ">=3.10.0, <3.12.0"
    anthropic     = "^0.3.11"
    httpx         = { extras = ["socks"], version = "^0.24.1" }
    lmql          = "^0.0.6.6"
    matplotlib    = "^3.7.2"
    numpy         = "^1.25.2"
    openai        = "^0.27.8"
    pandas        = "^2.1.0"
    tenacity      = "^8.2.3"
    tiktoken      = "^0.4.0"
    tqdm          = "^4.66.1"
    black         = { extras = ["jupyter"], version = "^23.9.1" }
    transformers  = { extras = ["torch"], version = "^4.33.2" }
    einops        = "^0.6.1"
    sentencepiece = "^0.1.99"

[build-system]
    build-backend = "poetry.core.masonry.api"
    requires      = ["poetry_core>=1.0.0"]
