[project]
    name = "LangMax"
    version = "0.1.0"
    description = "Leveraging the capabilities of LLMs to improve day-to-day tasks."
    authors = [
        { name = "Alex", email = "30626291+ipruning@users.noreply.github.com" },
    ]
    readme = "README.md"
    requires-python = ">= 3.12"
    dependencies = [
        "anthropic>=0.28.0",
        "autocorrect-py>=2.9.0",
        "chainlit>=1.1.202",
        "chromadb>=0.5.0",
        "datasets>=2.19.1",
        "einops>=0.8.0",
        "flask>=3.0.3",
        "gradio>=4.32.1",
        "httpx[socks]>=0.27.0",
        "langchain>=0.2.1",
        "langdetect>=1.0.9",
        "lark-oapi>=1.2.7",
        "litellm>=1.39.5",
        "llama-cpp-python[server]>=0.2.76",
        "llama-index>=0.10.41",
        "lmql>=0.7.3",
        "marimo>=0.6.13",
        "matplotlib>=3.9.0",
        "mlx-lm>=0.14.0",
        "mlx>=0.14.0",
        "numpy>=1.26.4",
        "ollama>=0.2.0",
        "openai>=1.30.5",
        "pandas>=2.2.2",
        "parea-ai>=0.2.164",
        "pathvalidate>=3.2.0",
        "portkey-ai>=1.2.4",
        "python-dotenv>=1.0.1",
        "ragas @ git+https://github.com/explodinggradients/ragas",
        "replicate>=0.26.0",
        "rich>=13.7.1",
        "sentencepiece>=0.2.0",
        "tenacity>=8.3.0",
        "tiktoken>=0.7.0",
        "tqdm>=4.66.4",
        "transformers[torch]>=4.41.2",
        "wandb>=0.17.0",
    ]

[build-system]
    requires      = ["hatchling"]
    build-backend = "hatchling.build"

[tool.rye]
    managed = true
    dev-dependencies = [
        "commitizen>=3.27.0",
        "coverage[toml]>=7.5.1",
        "debugpy>=1.8.1",
        "mypy>=1.10.0",
        "nox>=2024.4.15",
        "pre-commit>=3.7.1",
        "pytest-cov>=5.0.0",
        "pytest>=8.2.1",
        "ruff>=0.4.4",
    ]

[tool.hatch.metadata]
    allow-direct-references = true

[tool.hatch.build.targets.wheel]
    packages = ["src/tghl"]

[tool.ruff]
    # https://docs.astral.sh/ruff/configuration/
    # Exclude a variety of commonly ignored directories.
    exclude = [
        ".bzr",
        ".direnv",
        ".eggs",
        ".git",
        ".git-rewrite",
        ".hg",
        ".ipynb_checkpoints",
        ".mypy_cache",
        ".nox",
        ".pants.d",
        ".pyenv",
        ".pytest_cache",
        ".pytype",
        ".ruff_cache",
        ".svn",
        ".tox",
        ".venv",
        ".vscode",
        "__pypackages__",
        "_build",
        "buck-out",
        "build",
        "dist",
        "node_modules",
        "site-packages",
        "venv",
    ]

    # Same as Black.
    line-length  = 120
    indent-width = 4

[tool.ruff.lint]
    # Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
    # Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
    # McCabe complexity (`C901`) by default.
    select = ["E4", "E7", "E9", "F"]
    ignore = ["E501"]

    # Allow fix for all enabled rules (when `--fix`) is provided.
    fixable   = ["ALL"]
    unfixable = []

    # Allow unused variables when underscore-prefixed.
    dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
    # Like Black, use double quotes for strings.
    quote-style = "double"

    # Like Black, indent with spaces, rather than tabs.
    indent-style = "space"

    # Like Black, respect magic trailing commas.
    skip-magic-trailing-comma = false

    # Like Black, automatically detect the appropriate line ending.
    line-ending = "auto"

    # Enable auto-formatting of code examples in docstrings. Markdown,
    # reStructuredText code/literal blocks and doctests are all supported.
    #
    # This is currently disabled by default, but it is planned for this
    # to be opt-out in the future.
    docstring-code-format = false

    # Set the line length limit used when formatting code snippets in
    # docstrings.
    #
    # This only has an effect when the `docstring-code-format` setting is
    # enabled.
    docstring-code-line-length = "dynamic"

[tool.mypy]
    ignore_missing_imports = true
    strict                 = true

[tool.coverage.run]
    omit = [
        ".*",
        "*/site-packages/*",
        "*/__init__.py",
        "*/__main__.py",
        "*/tests",
        "*/excp.py",
    ]

[tool.coverage.report]
    fail_under   = 70
    show_missing = true

[tool.pytest.ini_options]
    python_files = ["test_*.py"]
    testpaths    = ["tests"]

[tool.pyright]
    venvPath = "."
    venv     = ".venv"
