[project]
    name = "langmax"
    version = "0.1.0"
    description = "Leveraging the capabilities of LLMs to improve day-to-day tasks."
    authors = [
        { name = "Alex", email = "30626291+ipruning@users.noreply.github.com" },
    ]
    readme = "README.md"
    requires-python = "~= 3.12"
    dependencies = [
        "anthropic~=0.34.2",
        "baml-py==0.56.1",
        "banks~=0.6.0",
        "bm25s~=0.2.1",
        "chromadb~=0.5.7",
        "commitizen~=3.29.0",
        "ebooklib>=0.18",
        "fastapi[standard]>=0.115.0",
        "fire~=0.6.0",
        "google-generativeai~=0.8.1",
        "great-tables~=0.11.1",
        "html2text>=2024.2.26",
        "httpx[socks]~=0.27.2",
        "jinja2~=3.1.4",
        "joblib>=1.4.2",
        "lancedb>=0.13.0",
        "langchain~=0.3.0",
        "libsql-experimental>=0.0.40",
        "lingua-language-detector>=2.0.2",
        "litellm~=1.48.0",
        "llama-cpp-python>=0.2.90",
        "llama-index~=0.11.12",
        "lmql~=0.7.3",
        "logfire[fastapi]>=0.53.0",
        "loguru>=0.7.2",
        "marimo~=0.8.19",
        "matplotlib~=3.9.2",
        "mlx~=0.17.3",
        "ollama~=0.3.3",
        "openai~=1.47.1",
        "pgvector>=0.3.3",
        "polars~=1.8.1",
        "psycopg[binary]>=3.2.2",
        "pyright~=1.1.381",
        "pystemmer>=2.2.0.1",
        "python-dotenv~=1.0.1",
        "python-fasthtml~=0.6.7",
        "rich~=13.8.1",
        "ruff~=0.6.7",
        "sglang[openai]~=0.3.1",
        "sqlite-utils>=3.37",
        "sqlite-vec>=0.1.1",
        "sqlmodel>=0.0.22",
        "tavily-python>=0.5.0",
        "tiktoken~=0.7.0",
        "transformers[torch]~=4.44.2",
        "wandb~=0.18.1",
    ]

[tool.pyright]
    pythonVersion    = "3.12"
    typeCheckingMode = "standard"
    venv             = ".venv"
    venvPath         = "."

[tool.uv]
    managed = true

[tool.ruff]
    exclude = [
        ".bzr",
        ".direnv",
        ".eggs",
        ".git",
        ".git-rewrite",
        ".hg",
        ".ipynb_checkpoints",
        ".mypy_cache",
        ".nox",
        ".pants.d",
        ".pyenv",
        ".pytest_cache",
        ".pytype",
        ".ruff_cache",
        ".svn",
        ".tox",
        ".venv",
        ".vscode",
        "__pypackages__",
        "_build",
        "buck-out",
        "build",
        "dist",
        "node_modules",
        "site-packages",
        "venv",
    ]
    indent-width = 4
    line-length = 120
    target-version = "py312"

[tool.ruff.lint]
    select    = ["A", "E", "F", "I", "N", "T100"]
    ignore    = ["E501", "F401"]
    fixable   = ["ALL"]
    unfixable = []

    dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
    quote-style                = "double"
    indent-style               = "space"
    skip-magic-trailing-comma  = false
    line-ending                = "auto"
    docstring-code-format      = true
    docstring-code-line-length = "dynamic"
