[tool.poetry]
    name        = "langmax"
    version     = "0.1.0"
    description = "Leveraging the capabilities of LLMs to improve day-to-day tasks."
    authors     = ["Alex <30626291+ipruning@users.noreply.github.com>"]
    readme      = "README.md"

[tool.poetry.dependencies]
    python        = ">=3.10.0, <3.12.0"
    anthropic     = "^0.7.7"
    black         = { extras = ["jupyter"], version = "^23.9.1" }
    datasets      = "^2.15.0"
    einops        = "^0.6.1"
    gradio        = "^4.8.0"
    httpx         = { extras = ["socks"], version = "^0.24.1" }
    lmql          = "^0.7.3"
    matplotlib    = "^3.7.2"
    mlx           = "^0.0.3"
    numpy         = "^1.25.2"
    openai        = "^1.3.7"
    pandas        = "^2.1.0"
    rich          = "^13.7.0"
    sentencepiece = "^0.1.99"
    tenacity      = "^8.2.3"
    tiktoken      = "^0.4.0"
    tqdm          = "^4.66.1"
    transformers  = { extras = ["torch"], version = "^4.33.2" }

[build-system]
    build-backend = "poetry.core.masonry.api"
    requires      = ["poetry_core>=1.0.0"]
