[project]
    name = "langmax"
    version = "0.1.0"
    description = "Leveraging the capabilities of LLMs to improve day-to-day tasks."
    authors = [
        { name = "Alex", email = "30626291+ipruning@users.noreply.github.com" },
    ]
    readme = "README.md"
    requires-python = "~= 3.12"
    dependencies = [
        "alive-progress~=3.1.5",
        "anthropic~=0.34.1",
        "autocorrect-py~=2.9.0",
        "baml-py>=0.54.0",
        "banks~=0.5.0",
        "bm25s[full]~=0.1.10",
        "chromadb~=0.5.4",
        "dowhy>=0.11.1",
        "einops>=0.8.0",
        "fastapi[standard]>=0.112.2",
        "fastcore>=1.7.4",
        "fire~=0.6.0",
        "google-generativeai~=0.7.2",
        "great-tables~=0.11.0",
        "httpx[socks]~=0.27.2",
        "inspect-ai>=0.3.25",
        "jinja2~=3.1.4",
        "langchain~=0.2.15",
        "langdetect~=1.0.9",
        "litellm~=1.44.14",
        "llama-cpp-python>=0.2.90",
        "llama-index-llms-openai>=0.2.1",
        "llama-index~=0.11.4",
        "lmql~=0.7.3",
        "logfire[fastapi]>=0.51.0",
        "loguru>=0.7.2",
        "marimo~=0.8.7",
        "matplotlib~=3.9.2",
        "mlx~=0.17.2",
        "ollama~=0.3.2",
        "openai~=1.43.0",
        "openpyxl~=3.1.5",
        "pathvalidate~=3.2.1",
        "polars~=1.6.0",
        "pypinyin~=0.52.0",
        "python-dotenv~=1.0.1",
        "python-fasthtml~=0.5.1",
        "replicate~=0.32.1",
        "rich~=13.8.0",
        "sentencepiece~=0.2.0",
        "sglang[openai]~=0.2.15",
        "sqlite-utils>=3.37",
        "sqlite-vec>=0.1.1",
        "sqlmodel>=0.0.22",
        "tiktoken~=0.7.0",
        "transformers[torch]~=4.44.2",
        "wandb~=0.17.8",
    ]

[tool.pyright]
    pythonVersion              = "3.12"
    reportArgumentType         = "warning"
    reportAttributeAccessIssue = "warning"
    reportRedeclaration        = "none"
    reportUnusedExpression     = "warning"
    typeCheckingMode           = "standard"
    venv                       = ".venv"
    venvPath                   = "."

[tool.uv]
    managed = true
    dev-dependencies = [
        "commitizen~=3.29.0",
        "coverage~=7.6.1",
        "debugpy~=1.8.5",
        "nox~=2024.4.15",
        "pre-commit~=3.8.0",
        "pyright~=1.1.378",
        "pytest-cov~=5.0.0",
        "pytest~=8.3.2",
        "ruff~=0.6.3",
    ]

[tool.ruff]
    exclude = [
        ".bzr",
        ".direnv",
        ".eggs",
        ".git",
        ".git-rewrite",
        ".hg",
        ".ipynb_checkpoints",
        ".mypy_cache",
        ".nox",
        ".pants.d",
        ".pyenv",
        ".pytest_cache",
        ".pytype",
        ".ruff_cache",
        ".svn",
        ".tox",
        ".venv",
        ".vscode",
        "__pypackages__",
        "_build",
        "buck-out",
        "build",
        "dist",
        "node_modules",
        "site-packages",
        "venv",
    ]
    indent-width = 4
    line-length = 120
    target-version = "py312"

[tool.ruff.lint]
    select = ["A", "E", "F", "I", "N", "T100"]
    ignore = ["E501"]

    fixable   = ["ALL"]
    unfixable = []

    dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
    quote-style                = "double"
    indent-style               = "space"
    skip-magic-trailing-comma  = false
    line-ending                = "auto"
    docstring-code-format      = true
    docstring-code-line-length = "dynamic"

[tool.coverage.run]
    source = ["src"]
    omit = [
        ".*",
        "*/site-packages/*",
        "*/__init__.py",
        "*/__main__.py",
        "*/tests/*",
        "*/excp.py",
    ]

[tool.coverage.report]
    fail_under = 75
    show_missing = true
    exclude_lines = [
        "def __repr__",
        "except ImportError:",
        "if __name__ == .__main__.:",
        "if self.debug:",
        "pass",
        "pragma: no cover",
        "raise NotImplementedError",
    ]

[tool.pytest.ini_options]
    python_files = ["test_*.py"]
    testpaths    = ["tests", "src"]
    addopts      = "-v --cov=src --cov-report=term-missing"
